spring:
  application:
    name: auth-service

  datasource:
    url: ${MySQL_URL}
    username: root
    password: ${MySQL_PASSWORD}

  main:
    banner-mode: off

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: hoangvanduc2504@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

logging:
  level:
    root: warn

app:
  domain:
    frontend: ${FRONTEND_DOMAIN}

  services:
    profile:
      url: ${PROFILE_SERVICE_URL}

jwt:
  secretKey: dAt62ISlQNyyt4dDObsfXv93IJ4mOHIGyqf/ECLbPQD/gERJ8wBaPISQyZTTE2PMQtEdsxtcyOFPFKsUJrQZoQ==
  expirationTime: 3600

outbound:
  identity:
    client-id: ${CLIENT_ID}
    client-secret: ${SECRET_KEY}
    redirect-uri: ${URL_REDIRECT}
    grant-types: authorization_code