spring:
  application:
    name: auth-service

  datasource:
    url: ${MySQL_URL}
    username: root
    password: ${MySQL_PASSWORD}

  main:
    banner-mode: off

  jpa:
    hibernate:
      ddl-auto: update

  Kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: all

server:
  port: 8080

logging:
  level:
    root: warn

app:
  domain:
    frontend: ${FRONTEND_DOMAIN}

  services:
    profile:
      url: ${PROFILE_SERVICE_URL}

jwt:
  secretKey: dAt62ISlQNyyt4dDObsfXv93IJ4mOHIGyqf/ECLbPQD/gERJ8wBaPISQyZTTE2PMQtEdsxtcyOFPFKsUJrQZoQ==
  expirationTime: 3600

outbound:
  identity:
    client-id: ${CLIENT_ID}
    client-secret: ${SECRET_KEY}
    redirect-uri: ${URL_REDIRECT}
    grant-types: authorization_code

