server:
  port: 8888

app:
  api-prefix: /v1

  domain:
    frontend: ${FRONTEND_DOMAIN}

spring:
  main:
    banner-mode: off

  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/api/external/auth/**,${app.api-prefix}/api/external/users/**
          filters:
            - StripPrefix=1
        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/api/external/users-detail/**,${app.api-prefix}/api/external/follows/**
          filters:
            - StripPrefix=1
        - id: study_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/api/external/categories/**,${app.api-prefix}/api/external/documents/**,${app.api-prefix}/api/external/favorites/**
          filters:
            - StripPrefix=1
        - id: interaction_service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/api/external/comments/**,${app.api-prefix}/api/external/external/ratings/**,${app.api-prefix}/api/external/reports/**
          filters:
            - StripPrefix=1
        - id: notification_service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/api/external/user-notifications/**
          filters:
            - StripPrefix=1
        - id: chat_service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/api/external/chats/**,${app.api-prefix}/api/external/chat-messages/**,${app.api-prefix}/api/external/conversations/**,${app.api-prefix}/api/external/participant-infos/**,/ws
          filters:
            - StripPrefix=1

logging:
  level:
    root: warn