spring:
  application:
    name: interaction-service

  datasource:
    url: ${MySQL_URL}
    username: root
    password: ${MySQL_PASSWORD}

  main:
    banner-mode: off

  jpa:
    hibernate:
      ddl-auto: update

  Kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: all

      properties:
        # Đảm bảo mỗi message chỉ được ghi một lần, tránh duplicate khi retry
        enable.idempotence: true

        # Số request tối đa được gửi đồng thời trên một kết nối (giữ 5 để vừa hiệu năng vừa đảm bảo thứ tự khi bật idempotence)
        max.in.flight.requests.per.connection: 5

        # Thời gian tối đa để producer cố gắng gửi một message (bao gồm cả retry)
        delivery.timeout.ms: 120000

        # Thời gian tối đa chờ ACK của broker cho mỗi lần gửi trước khi timeout và retry
        request.timeout.ms: 30000
    consumer:
      group-id: interaction-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8084

logging:
  level:
    root: warn

app:
  domain:
    frontend: ${FRONTEND_DOMAIN}

  services:
    study:
      url: ${STUDY_SERVICE_URL}
    profile:
      url: ${PROFILE_SERVICE_URL}
