spring:
  application:
    name: file-service

  main:
    banner-mode: off

server:
  port: 8083

logging:
  level:
    root: warn

app:
  cloud:
    name: ${CLOUD_NAME}
    key: ${CLOUD_KEY}
    secret: ${CLOUD_SECRET}
