spring:
  application:
    name: chat-service

  datasource:
    url: ${MySQL_URL}
    username: root
    password: ${MySQL_PASSWORD}
  ai:
    openai:
      api-key: ${API_KEY}
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.5-flash
    retry:
      max-attempts: 3
      backoff:
        initial-interval: 30s
        multiplier: 2
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

  main:
    banner-mode: off

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8086

logging:
  level:
    root: warn

jwt:
  secretKey: dAt62ISlQNyyt4dDObsfXv93IJ4mOHIGyqf/ECLbPQD/gERJ8wBaPISQyZTTE2PMQtEdsxtcyOFPFKsUJrQZoQ==

app:
  domain:
    frontend: ${FRONTEND_DOMAIN}

  services:
    file:
      url: ${FILE_SERVICE_URL}
    interaction:
      url: ${INTERACTION_SERVICE_URL}
    profile:
      url: ${PROFILE_SERVICE_URL}
    study:
      url: ${STUDY_SERVICE_URL}