spring:
  application:
    name: learning-service

  datasource:
    url: ${MySQL_URL}
    username: root
    password: ${MySQL_PASSWORD}

  main:
    banner-mode: off

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082

logging:
  level:
    root: warn

app:
  services:
    file: http://localhost:8083