spring:
  application:
    name: learning-service

  datasource:
    url: ${MySQL_URL}
    username: root
    password: ${MySQL_PASSWORD}

  main:
    banner-mode: off

  jpa:
    hibernate:
      ddl-auto: update

  Kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: all

server:
  port: 8082

logging:
  level:
    root: warn

app:
  domain:
    frontend: ${FRONTEND_DOMAIN}

  services:
    file:
      url: ${FILE_SERVICE_URL}
    profile:
      url: ${PROFILE_SERVICE_URL}
